<div></div>

<div></div>

\begin{align*}
\textbf{DEVOIR 2}
\end{align*}

<div></div>

<div style="text-align:center; font-family:Times New Roman; font-size:22px">
    ROMAN NAKHUDA 20207082
</div>

<div style="text-align:center; font-family:Times New Roman; font-size:22px">
    LUCKY KHOUNVONGSA 20172476
</div>
<div style="text-align:center; font-family:Times New Roman; font-size:22px">
    ANGE LILIAN TCHOMTCHOUA TOKAM 20210129
</div>

<div></div>

<div></div>

<div style="text-align:center; font-family:Times New Roman; font-size:22px">
    OPTIMISATION LINEAIRE - IFT2505
</div>
<div style="text-align:center; font-family:Times New Roman; font-size:18px">
     PROFESSEUR FABIEN BASTIN
</div>

<div></div>

<div></div>

<div style="text-align:center; font-family:Times New Roman; font-size:16px">
    Université de Montréal
</div>
<div style="text-align:center; font-family:Times New Roman; font-size:16px">
    À remettre le 16 Octobre 2023 à 23:59
</div>

<div></div>

<div></div>

## $\textbf{Question 1}$

$\textbf{Soit le problème: }$

\begin{align*} 
\begin{array}{l c c c c c c c} 
  \min\  x  = &  -2x    & - &  y   & - &  3z  &  &   \\ 
  \text{tel que }   &  2x  & + &  3y  & + &  4z   &  \leq  & 120  \\ 
            &  x      & + &  2y  &&&  \leq  & 50  \\ 
            &  x      && + &&  2z  &  \leq  & 50  \\ 
            & x, && y, && z & \geq & 0      \\ 
\end{array} 
\end{align*}

- $\textbf{(a) Resolvons le problème à la main avec la méthode du simplexe.}$

$\text{On transforme le problème sous la forme standard à l'introduction des variables d'écarts}$ $s_1,$ $s_2$ $\text{et}$ $s_2.$

$\text{On obtient:}$

\begin{align*} 
\begin{array}{l c c c c c c c c c c} 
  \min\  x  = &  -2x    & - &  y   & - &  3z  &  &   \\ 
  \text{tel que }   &  2x  & + &  3y  & + &  4z  & + & s_1 & && && =  & 120  \\ 
            &  x      & + &  2y  && && & + & s_2 & &&  =  & 50  \\ 
            &  x      && & + & 2z &&  && &+& s_3&  =  & 50  \\ 
            & x, && y, && z, && s_1, && s_2, && s_3 & \geq & 0      \\ 
\end{array} 
\end{align*}

$\text{Avec les variables dans la base}$ $s_1,$ $s_2$ $\text{et}$ $s_2,$ $\text{On obtient le tableau du simplexe suivant;}$

\begin{align*}
\begin{array}{c|cccccc|c}
& x & y & z & s_1 & s_2 & s_3 & \text{T.D.}\\
\hline
s_1 & 2 & 3 & 4 & 1 & 0 & 0 & 120 \\
s_2 & 1 & 2 & 0 & 0 & 1 & 0 & 50 \\
s_3 & 1 & 0 & \color{red} 2 & 0 & 0 & 1 & 50 \\
\hline
-z  & -2 & -1 & -3 & 0 & 0 & 0 & 0\\
\end{array}
\end{align*}

$\text{On prend}$ $z$ $\text{comme variable d'entrée et}$ $s_3$ $\text{comme variable de sortie.}$

\begin{align*}
\begin{array}{c|cccccc|c}
& x & y & z & s_1 & s_2 & s_3 & \text{T.D.}\\
\hline
s_1 & 0 & \color{red}3 & 0 & 1 & 0 & 0 & 20 \\
s_2 & 1 & 2 & 0 & 0 & 1 & 0 & 50 \\
z & 1/2 & 0 & 1 & 0 & 0 & 1/2 & 25 \\
\hline
-z  & -1/2 & -1 & 0 & 0 & 0 & 3/2 & 75\\
\end{array}
\end{align*}

$\text{On prend}$ $y$ $\text{comme variable d'entrée et}$ $s_1$ $\text{comme variable de sortie.}$

\begin{align*}
\begin{array}{c|cccccc|c}
& x & y & z & s_1 & s_2 & s_3 & \text{T.D.}\\
\hline
y & 0 & 1 & 0 & 1/3 & 0 & 0 & 20/3 \\
s_2 & \color{red}1 & 0 & 0 & -2/3 & 1 & 0 & 110/3 \\
z & 1/2 & 0 & 1 & 0 & 0 & 1/2 & 25 \\
\hline
-z  & -1/2 & 0 & 0 & 1/3 & 0 & 3/2 & 245/3\\
\end{array}
\end{align*}

$\text{On prend}$ $x$ $\text{comme variable d'entrée et}$ $s_2$ $\text{comme variable de sortie.}$

\begin{align*}
\begin{array}{c|cccccc|c}
& x & y & z & s_1 & s_2 & s_3 & \text{T.D.}\\
\hline
y & 0 & 1 & 0 & 1/3 & 0 & 0 & 20/3 \\
x & 1 & 0 & 0 & -2/3 & 1 & 0 & 110/3 \\
z & 0 & 0 & 1 & 0 & 1/3 & 1/2 & 20/3 \\
\hline
-z  & 0 & 0 & 0 & 0 & 1/2 & 3/2 & 100\\
\end{array}
\end{align*}

$\text{Donc,}$

\begin{align*}
&x=110/3,\ y=20/3,\ z=20/3 \\
&s_1=s_2=s_3=0 
\end{align*}
$\text{et la valeur optimale du problème est}$ $z^{\star}=100$.

- $\textbf{(b) Resolvons le problème avec la méthode du simplexe revisée.}$

$\text{Considérons le problème sous forme canonique:}$
\begin{align*} 
\begin{array}{l c c c c c c c c c c} 
  \min\  x  = &  -2x    & - &  y   & - &  3z  &  &   \\ 
  \text{tel que }   &  2x  & + &  3y  & + &  4z  & + & s_1 & && && =  & 120  \\ 
            &  x      & + &  2y  && && & + & s_2 & &&  =  & 50  \\ 
            &  x      &&  & + & 2z&  && &+& s_3&  &=  & 50  \\ 
            & x, && y, && z, && s_1, && s_2, && s_3 & \geq & 0      \\ 
\end{array} 
\end{align*}

$\text{On se limite à:}$
\begin{align*}
\begin{array}{c|ccc|c}
\text{Var} && && x_B\\
\hline
s_1 & 1 & 0 & 0 & 120 \\
s_2 & 0 & 1 & 0 & 50 \\
s_3 & 0 & 0 & 1 & 50 \\
\end{array}
\end{align*}

$\text{On a,}$ $\lambda ^T = c^T_B B^-1 =
\begin{pmatrix}
0 & 0 & 0 
\end{pmatrix} B^{-1} =
\begin{pmatrix}
0 & 0 & 0 
\end{pmatrix} $

$\text{et}$ $r^T_D = C^T_D - \lambda ^T D = 
\begin{pmatrix}
-2 & -1 & -3 
\end{pmatrix}$

$\text{On obtient le dictionnaire;}$
\begin{align*}
\begin{array}{ccccc}
s_1 & = & 120 & -2x &-3y &-4z\\
s_2 & = & 50 & -x &-2y \\
s_3 & = & 50 & -x && -2z\\
\hline
z & = & 0 & -2x &-y &-3z\\
\end{array}
\end{align*}

$\text{La base}$ $B$ $\text{est constituée des colonnes associées aux variables}$ $s_1,$ $s_2$ $\text{et}$ $s_3.$

\begin{align*}
    & B =
    \begin{pmatrix}
         1 & 0 & 0 \\
         0 & 1 & 0 \\
         0 & 0 & 1
    \end{pmatrix} \\ \\
\end{align*}
$\text{Le variable entrante retenue est}$ $z,$ $\text{et on construit le tableau}$
\begin{array}{c|ccc|c|c}
          \text{Var} && && x_B &x\\
          \hline
          s_1 & 1 & 0 & 0 & 120 &4\\
          s_2 & 0 & 1 & 0 & 50 &0\\
          s_3 & 0 & 0 & 1 & 50 &\color{red}2\\\
\end{array}

$\text{Après le pivot,}$
\begin{array}{c|ccc|c}
          \text{Var} && && x_B \\
          \hline
          s_1 & 1 & 0 & -2 & 20 \\
          s_2 & 0 & 1 & 0 & 50 \\
          z & 0 & 0 & 1/2 & 25 \\
\end{array}
 

$\text{Nous avons également}$ $C^T_B = 
\begin{pmatrix}
0 & 0 & -3
\end{pmatrix}
$ $\\$
$\text{et}$ $\lambda^T = c^T_B B^{-1} =
\begin{pmatrix}
0 & 0 & -3
\end{pmatrix}
\begin{pmatrix}
     1 & 0 & -2 \\
     0 & 1 & 0 \\
     0 & 0 & 1/2
\end{pmatrix} 
 = \begin{pmatrix}
     0 & 0 & -3/2
\end{pmatrix}$


$\text{Les coûts reduits se calculent de manière similaire}$ $\\$
\begin{align*}
    r^T_D & = C^T_D - \lambda^T D \\
    & = 
        \begin{pmatrix}
            -2 & -1 & 0
        \end{pmatrix}
        - \begin{pmatrix}
            0 & 0 & -3/2
          \end{pmatrix}
          \begin{pmatrix}
            2 & 3 & 0 \\
            1 & 2 & 0 \\
            1 & 0 & 1
          \end{pmatrix} \\
    & = 
        \begin{pmatrix}
            -1/2 & -1 & 3/2
        \end{pmatrix} \\
    & = 
        \begin{pmatrix}
            r_1 & r_2 & r_3
        \end{pmatrix}
\end{align*}

$\text{Par la suite, On prend}$ $y$ $\text{comme variable entrante, on obtient;}$

\begin{align*}
y = 
    \begin{pmatrix}
         1 & 0 & -2 \\
         0 & 1 & 0 \\
         0 & 0 & 1/2
    \end{pmatrix}
    \begin{pmatrix}
         2 \\
         1 \\
         1 
    \end{pmatrix}
    =
    \begin{pmatrix}
         3 \\
         2 \\
         0 
     \end{pmatrix}
\end{align*} \\

\begin{array}{c|ccc|c|c}
    \text{Var} && && x_B &y\\
    \hline
    s_1 & 1 & 0 & -2 & 20 &\color{red}3 \\
    s_2 & 0 & 1 & 0 & 50 &2\\
    z & 0 & 0 & 1/2 & 25 &0\\
\end{array}

$\text{Après le pivot:}$
\begin{array}{c|ccc|c}
    \text{Var} && && x_B \\
    \hline
    y & 1/3 & 0 & -2/3 & 20/3 \\
    s_2 & -2/3 & 1 & 4/3 & 110/3 \\
    z & 0 & 0 & 1/2 & 25 \\
\end{array}

$\text{Nous avons également}$ $C^T_B = 
\begin{pmatrix}
-1 & 0 & -3
\end{pmatrix}
$ $\\$
$\text{et}$ $\lambda^T = c^T_B B^{-1} =
\begin{pmatrix}
-1 & 0 & -3
\end{pmatrix}
\begin{pmatrix}
     1/3 & 0 & -2/3 \\
     -2/3 & 1 & 4/3 \\
     0 & 0 & 1/2
\end{pmatrix} 
 = \begin{pmatrix}
     -1/3 & 0 & -5/6
\end{pmatrix}$


\begin{align*}
    r^T_D =
    & 
        \begin{pmatrix}
            -2 & 0 & 0
        \end{pmatrix}
        - \begin{pmatrix}
            -1/3 & 0 & -5/6
          \end{pmatrix}
          \begin{pmatrix}
            2 & 1 & 0 \\
            1 & 0 & 0 \\
            1 & 0 & 1
          \end{pmatrix} \\
    & = 
        \begin{pmatrix}
            -1/2 & 1/3 & 5/6
        \end{pmatrix} \\
    & = 
        \begin{pmatrix}
            r_1 && r_2 && r_3
        \end{pmatrix}
\end{align*}

$\text{Le variable entrante retenue est}$ $x,$ $\text{et on construit le tableau}$

\begin{align*}
x = 
    \begin{pmatrix}
         1/3 & 0 & -2/3 \\
         -2/3 & 1 & 4/3 \\
         0 & 0 & 1/2
    \end{pmatrix}
    \begin{pmatrix}
         2 \\
         1 \\
         1 
    \end{pmatrix}
    =
    \begin{pmatrix}
         0 \\
         1 \\
         1/2 
     \end{pmatrix}
\end{align*} \\

\begin{array}{c|ccc|c|c}
    \text{Var} && && x_B &x\\
    \hline
    y & 1/3 & 0 & -2/3 & 20/3 &0 \\
    s_2 & -2/3 & 1 & 4/3 & 110/3 &\color{red}1\\
    z & 0 & 0 & 1/2 & 25 &1/2\\
\end{array}

$\text{Après le pivot et la variable sortante}$ $s_2,$

\begin{array}{c|ccc|c}
    \text{Var} && && x_B\\
    \hline
    y & 1/3 & 0 & -2/3 & 20/3 \\
    x & -2/3 & 1 & 4/3 & 110/3\\
    z & 1/3 & -1/2 & -1/6 & 20/3\\
\end{array}

$\text{On a,}$ $\lambda^T =
\begin{pmatrix}
-1 & -2 & -3
\end{pmatrix}
\begin{pmatrix}
     1/3 & 0 & -2/3 \\
     -2/3 & 1 & 4/3 \\
     1/3 & -1/2 & 1/6
\end{pmatrix} 
 = \begin{pmatrix}
     0 & -1/2 & -3/2
\end{pmatrix}$

\begin{align*}
    r^T_D =
    & 
        \begin{pmatrix}
            0 & 0 & 0
        \end{pmatrix}
        - \begin{pmatrix}
            0 & -1/2 & -3/2
          \end{pmatrix}
          \begin{pmatrix}
            1 & 0 & 0 \\
            0 & 1 & 0 \\
            0 & 0 & 1
          \end{pmatrix} \\
    & = 
        \begin{pmatrix}
            0 & 1/2 & 3/2
        \end{pmatrix} \\
    & \implies r_1 = 0, r_2 = 1/2, r_3 = 3/2
        
\end{align*}

$\text{D'où la solution optimale}$
$x = 
\begin{pmatrix}
    110/3, &20/3, &20/3, &0, &0, &0
\end{pmatrix}$

- $\textbf{(c) Utilisons  JuMP en Julia pour vérifier la solution du problème.}$

In [1]:
using JuMP, HiGHS

In [2]:
m = Model(HiGHS.Optimizer)

@variable(m, 0 <= x)
@variable(m, 0 <= y)
@variable(m, 0 <= z)

@constraint(m, 2x + 3y + 4z <= 120.0)
@constraint(m, x + 2y <= 50.0)
@constraint(m, x + 2z <= 50.0)

@objective(m, Min, -2x-y-3z)

print(m)

Min -2 x - y - 3 z
Subject to


2 x + 3 y + 4 z <= 120
 x + 2 y <= 50
 x + 2 z <= 50
 x >= 0
 y >= 0
 z >= 0


In [3]:
status = optimize!(m)

Running HiGHS 1.5.3 [date: 1970-01-01, git hash: 45a127b78]
Copyright (c) 2023 HiGHS under MIT licence terms
Presolving model
3 rows, 3 cols, 7 nonzeros
3 rows, 3 cols, 7 nonzeros
Presolve : Reductions: rows 3(-0); columns 3(-0); elements 7(-0) - Not reduced
Problem not reduced by presolve: solving the LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0    -5.9999935790e+00 Ph1: 3(15); Du: 3(5.99999) 0s
          3    -1.0000000000e+02 Pr: 0(0) 0s
Model   status      : Optimal
Simplex   iterations: 3
Objective value     : -1.0000000000e+02
HiGHS run time      :          0.01


In [4]:
println([value(x), value(y), value(z)])

[50.0, 0.0, -0.0]


In [5]:
function pivot!(M::Matrix, i::Int, j::Int)
    m, n = size(M)
    @assert M[i, j] != 0
    M[i, :] = M[i, :]/M[i, j]
    for k in setdiff(1:m, i)
        M[k, :] -= M[k, j] * M[i, :]
    end
    return M
end

function getReducedCosts(M::Matrix)
    m, n = size(M)
    return M[end, 1:n-1]
end
function getxB(M::Matrix)
    m, n = size(M)
    return M[1:m-1, end]
end
function enteringVar(M::Matrix)
    rc = getReducedCosts(M)
    index = argmin(rc)
    return rc[index] >= 0 ? -1 : index
end
function exitingVarIndex(M::Matrix{T}, enteringVar::Int) where T
    col = M[1:end-1, enteringVar]
    xB = getxB(M)
    m, n = size(M)
    index = -1
    val = T(Inf)
    for i in 1:m-1
        if (col[i] > 0) && (xB[i]/col[i] < val)
            val = xB[i]/col[i]
            index = i
        end
    end
    return index
end
function isOneHot(v::Vector)
    n = length(v)
    return (sum(iszero, v) == n-1) && (sum(isone, v) == 1)
end 
function isoptimal(M)
    return enteringVar(M) == -1
end
function findInitialBasis!(M::Matrix)
    m, n = size(M)
    m-=1
    n-=1
    basis = [-1 for _ in 1:m]
    for i in 1:n
        if isOneHot(M[1:end-1, i])
            index = findfirst(isone, M[:, i])
            basis[index] = i
        end
    end
    @assert !any(t-> t == -1, basis) "problem not caconical"
    for i in 1:m
        j = basis[i]
        pivot!(M, i, j)
    end
    return basis
end
function simplexSolver(A::Matrix{T}, b::Vector, c::Vector; verbose::Bool = false) where T
    M = [A b; c' 0]
    basis = findInitialBasis!(M)
    k = 1
    nmax = 1000
    while !isoptimal(M) && k < nmax
        k+=1
        verbose && display(M)
        entering = enteringVar(M)
        entering == -1 && (println("------------"); return T[-1, -1])
        leaving = exitingVarIndex(M, entering)
        leaving == -1 && (println("------------"); return T[-1, -1])
        verbose && @show (entering, leaving)
        basis[leaving] = entering
        pivot!(M, leaving, entering)
    end
    verbose && display(M)
    m, n = size(M)
    xstar = zeros(T, n - 1)
    xstar[basis] = getxB(M)
    return xstar
end

simplexSolver (generic function with 1 method)

In [6]:
A=[2//1 3 4 1 0 0 ; 
    1 2 0 0 1 0;
    1 0 2 0 0 1;
]
b=[120, 50, 50]
c = [-2,-1,-3,0,0,0]

6-element Vector{Int64}:
 -2
 -1
 -3
  0
  0
  0

In [7]:
simplexSolver(A, b, c, verbose=true)

4×7 Matrix{Rational{Int64}}:
  2//1   3//1   4//1  1//1  0//1  0//1  120//1
  1//1   2//1   0//1  0//1  1//1  0//1   50//1
  1//1   0//1   2//1  0//1  0//1  1//1   50//1
 -2//1  -1//1  -3//1  0//1  0//1  0//1    0//1

4×7 Matrix{Rational{Int64}}:
  0//1   3//1  0//1  1//1  0//1  -2//1  20//1
  1//1   2//1  0//1  0//1  1//1   0//1  50//1
  1//2   0//1  1//1  0//1  0//1   1//2  25//1
 -1//2  -1//1  0//1  0//1  0//1   3//2  75//1

4×7 Matrix{Rational{Int64}}:
  0//1  1//1  0//1   1//3  0//1  -2//3   20//3
  1//1  0//1  0//1  -2//3  1//1   4//3  110//3
  1//2  0//1  1//1   0//1  0//1   1//2   25//1
 -1//2  0//1  0//1   1//3  0//1   5//6  245//3

4×7 Matrix{Rational{Int64}}:
 0//1  1//1  0//1   1//3   0//1  -2//3   20//3
 1//1  0//1  0//1  -2//3   1//1   4//3  110//3
 0//1  0//1  1//1   1//3  -1//2  -1//6   20//3
 0//1  0//1  0//1   0//1   1//2   3//2  100//1

(entering, leaving) = (3, 3)
(entering, leaving) = (2, 1)
(entering, leaving) = (1, 2)


6-element Vector{Rational{Int64}}:
 110//3
  20//3
  20//3
   0//1
   0//1
   0//1

## $\textbf{Question 2}$

$\text{On va résoudre la démonstration par contradiction}$

$\text{On suppose}$ $\urcorner p$ $\text{ ainsi: }$
$\text{On suppose que toutes solutions de base réalisable dégénérée}$ $\\$ $\text{peuvent être optimales en satisfaisant}$ $r_j \geq 0$ $\text{pour tout }$ $j.$

$\text{On considère ainsi le problème linéaire suivant: }$

$\text{Considérons le programme linéaire suivant:}$
\begin{array}{ccccc}
    \max\ &x_1  & + & x_2\\
    \text{tel que} &x_1 & + & x_2  & \leq & 0\\
                   &&& x_2  & \leq &0\\
    &x_1, &&x_2 & \geq &0\\
\end{array}


\begin{array}{ccccccccc}
    &-\min\ &-x_1  & - & x_2\\
    &\text{tel que} &x_1 & + & x_2 & + & x_3 && = & 0\\
    \implies &               &&& x_2 && + &x_4 &  = &0\\
    &&x_1, &&x_2, && x_3, & x_4 & \geq &0\\
\end{array}

$\text{En utilisant la méthode du simplexe on a:}$

\begin{array}{ccccc}
    &x_1 & x_2 & x_3 &x_4 & b\\
    x_3 &\color{red}1   & 1   & 1   & 0  & 0\\
    x_4 &0   & 1   & 0   & 1  & 0\\
    c^T& -1 & -1 & 0 &0 &0\\
\end{array}

$\text{Il y a des coéficientes reduits négatifs, par la suite on a:}$

\begin{array}{ccccc}
    &x_1 & x_2 & x_3 &x_4 & b\\
    &1   & 1   & 1   & 0  & 0\\
    &0   & 1   & 0   & 1  & 0\\
    c^T& 0 & 0 & 1 &0 &0\\
\end{array}

$\text{On obtient donc la solution optimale}$ $(0, 0, 0, 0)$ $\text{et}$ $z=0$ $\text{avec des coûts réduits négatifs,}$ $\\$ $\text{ce qui mène à une contradiction à}$ $\urcorner p:$

$\text{Par conséquent on a prouvé par contradiction qu'une solution de base peut être optimale en satisfaisant}$ $r_j \geq 0$

## $\textbf{Question 3}$

- $\textbf{(a) Identifions les variables de base Initiales et Determinons}$ $B^{-1}$ $\textbf{:}$
\begin{align*}
    \begin{array}{cccccc}
    x_1 & x_2 & x_3 & x4 & x_5 & b \\
    a & b & c & 1 & 0 & 6 \\
    -1 & 2 & e & 0 & 1 & 1 \\
    d & -1 & 3 & 0 & 0 & 0 \\
    \end{array}
\end{align*}

$\text{Les variables de base initiales sont}$ $x_4$ $\text{et}$ $x_5$ $\text{car elles leurs coeficients forment la matrice indentité.}$

\begin{align*}
    B = 
    \begin{pmatrix}
        1 & 0\\
        0 & 1 \\
    \end{pmatrix}
    B^{-1} = 
    \begin{pmatrix}
        1 & 0 \\
        0 & 1
    \end{pmatrix}
\end{align*}

- $\textbf{(b) Identifions les variables de base Initiales et Determinons}$ $B^{-1}$ $\textbf{sur la deuxième itération:}$

\begin{align*}
    \begin{array}{cccccc}
    x_1 & x_2 & x_3 & x4 & x_5 & b \\
    f & 2/3 & 2/3 & 1/3 & 0 & i \\
    g & h & -1/3 & 1/3 & 1 & j \\
    0 & 1/3 & k & l & m & n \\
    \end{array}
\end{align*}

$\text{Les variables de base initiales sont}$ $x_1$ $\text{et}$ $x_5$ 

$\text{On obtient}$ $B^{-1}$ $\text{directement depuis le nouveau tableau du simplexe:}$
\begin{align*}
    B^{-1} = 
    \begin{pmatrix}
        1/3 & 0 \\
        1/3 & 1
    \end{pmatrix}
\end{align*}

- $\textbf{(c) Trouvons les valeurs de a, b, c, d, e, f, g, h, i, j, k, l, m, n}$

$\text{On refait les étapes du simplexe sur le tableau initiale, on a;}$

\begin{align*}
    \begin{array}{cccccc}
    x_1 & x_2 & x_3 & x4 & x_5 & b \\
    \color{red}a & b & c & 1 & 0 & 6 \\
    -1 & 2 & e & 0 & 1 & 1 \\
    d & -1 & 3 & 0 & 0 & 0 \\
    \end{array}
\end{align*}

$x_1$ $\text{entre dans la base donc on divise toute la première ligne par}$ $a$ $\text{et on rend}$ $x_1$ $\text{variable isolée en additionant la ligne 1 à la ligne 2 et en soustrayant d fois la ligne 1 à la ligne 3, on obtient}:$

\begin{align*}
    \begin{array}{cccccc}
    x_1 & x_2 & x_3 & x4 & x_5 & b \\
    1 & b/a & c/a & 1/a & 0 & 6/a \\
    0 & 2+(b/a) & e+(c/a) & 0+(1/a) & 1 & 1+(6/a) \\
    0 & -1-d(b/a) & 3-d(c/a) & 0-d(1/a) & 0 & 0-d(6/a) \\
    \end{array}
\end{align*}

$\text{En comaparant le tableau obtenu avec le premier et le deuxième tableau du simplexe donnés par l'énoncé, on a}$ $\\$
\begin{align*}
\begin{array}{ll}
&f=1, g=0, a=3, m=0,\\
b/a = 2/3 &\implies b=2,\\
c/a = 2/3 &\implies c=2, \\
i=6/a &\implies i=2,\\
h=2+b/a &\implies h=8/3,\\
e+(c/a) = -1/3 &\implies e=-1,\\
j=1+(6/a) &\implies j=3,\\
-1-d(b/a)=1/3 &\implies d=-2,\\
k=3-d(c/a) &\implies k=13/3,\\
l=0-d(1/a) &\implies l=2/3,\\
n = 0 - d(6/a) &\implies n=4
\end{array}
\end{align*}

- $\textbf{(d) Tableau de la deuxième itération}$ $\\$
$\text{En remplaçant les valeurs obtenues en}$ $c)$ $\text{on obtient le tableau suivant;}$


\begin{align*}
    \begin{array}{c|ccccc|c}
    &x_1 & x_2 & x_3 & x4 & x_5 & b \\
    \hline
    x_1 &1 & 2/3 & 2/3 & 1/3 & 0 & 2 \\
    x_5 &0 & 8/3 & -1/3 & 1/3 & 1 & 3 \\
    \hline
    r^T &0 & 1/3 & 13/3 & 2/3 & 0 & 4 \\
    \end{array}
\end{align*}

$\text{On a la solution réalisable non dégénérée qui est}$ $(x_1, x_2, x_3, x_4, x_5) = (2, 0, 0, 0, 3)$ $\text{avec}$ $z^* = -4$ $\text{la solution optimale car tous les coûts réduits sont non négatifs.}$ $\\$

- $\textbf{(e) Écrivons le problème initial}$ $\\$
$\text{En remplaçant les valeurs obtenues en}$ $c)$ $\text{dans le tableau initial du simplexe, on obtient;}$

\begin{align*} 
\begin{array}{l c c c c c c c c c} 
  \min\  z  =       &-2x_1   & - &  x_2  & + &  3x_3   \\ 
  \text{tel que }   &  3x_1  & + &  2x_2  & + &  2x_3 & + &  x_4   &&  =  & 6  \\ 
                    &  -x_1  & + &  2x_2  & + & -x_3 && + &  x_5   &   =  & 1  \\ 
            & x_1, && x_2, && x_3 , && x_4, & x_5 & \geq & 0      \\ 
\end{array} 
\end{align*}

## $\textbf{Question 4}$

$\text{Soit le système}$

\begin{align*}
    x_1 + x_2 \leq 1&\\
    x_1 + x_2 \geq 2&\\
    x_1, x_2 \geq 0&\\
\end{align*}

$\text{Utilisons la phase I du simplexe pour montrer que ce système ne possède pas de solution}$

$\text{On converti le problème sous forme standard à l'introduction de deux variables artificiels}$ $x_3,$ $x_4,$ $\text{on a;}$

\begin{array}{ccccc}
    \min\ &&&x_3  &+x_4\\
    \text{tel que}&x_1  &+x_2  &+x_3 &&= 1\\
    &x_1  &+x_2  &&-x_4 &= 2\\
    &x_1, &x_2, &x_3, &x_4 &\geq 0\\
\end{array}

$\text{On obtient le problème sous forme de tableau}$
\begin{array}{ccccc}
    &x_1 & x_2 & x_3 &x_4 & b\\
    &1   & 1   & 1   & 0  & 1\\
    &1   & 1   & 0   & -1  & 2\\
    c^T& 0   &0 &1 &1 &0\\
\end{array}
$\text{Pour avoir les colonnes de la matrice identité, on multipli la deuxième ligne par}$ $-1$ $\text{on a;}$
\begin{array}{ccccc}
    &x_1 & x_2 & x_3 &x_4 & b\\
    &1   & 1   & 1   & 0  & 1\\
    &-1   &-1   & 0   & 1  & -2\\
    c^T& 0   &0 &1 &1 &0\\
\end{array}

$\text{Pour obtenir une solution de base réalisable, il faut annuler les
coefficients de}$ $x_3$ $\text{et}$ $x_4.$ $\text{Nous obtenons le nouveau tableau}$
\begin{array}{ccccc}
    &x_1 & x_2 & x_3 &x_4 & b\\
    &1   & 1   & 1   & 0  & 1\\
    &-1   & -1   & 0   & 1  & -2\\
c^T &0   &0    &0    &0   &1\\
\end{array}

$\text{On ne peut donc pas continuer la résolution du système en utilisant le simplexe comme d’ordinaire car}$ $\\$ $\text{on a un système linéaire incompatible qui n'a aucune solution.}$ 
\begin{array}{rrrrrrr}
    &&&&&&&&&&&&&&&&&&&&&&QED 
\end{array}

$\text{La partie en julia;}$

In [8]:
function pivot!(M::Matrix, i::Int, j::Int)
    m, n = size(M)
    @assert M[i, j] != 0
    M[i, :] = M[i, :]/M[i, j]
    for k in setdiff(1:m, i)
        M[k, :] -= M[k, j] * M[i, :]
    end
    return M
end

function getReducedCosts(M::Matrix)
    m, n = size(M)
    return M[end, 1:n-1]
end
function getxB(M::Matrix)
    m, n = size(M)
    return M[1:m-1, end]
end
function enteringVar(M::Matrix)
    rc = getReducedCosts(M)
    index = argmin(rc)
    return rc[index] >= 0 ? -1 : index
end
function exitingVarIndex(M::Matrix{T}, enteringVar::Int) where T
    col = M[1:end-1, enteringVar]
    xB = getxB(M)
    m, n = size(M)
    index = -1
    val = T(Inf)
    for i in 1:m-1
        if (col[i] > 0) && (xB[i]/col[i] < val)
            val = xB[i]/col[i]
            index = i
        end
    end
    return index
end
function isOneHot(v::Vector)
    n = length(v)
    return (sum(iszero, v) == n-1) && (sum(isone, v) == 1)
end 
function isoptimal(M)
    return enteringVar(M) == -1
end
function findInitialBasis!(M::Matrix)
    m, n = size(M)
    m-=1
    n-=1
    basis = [-1 for _ in 1:m]
    for i in 1:n
        if isOneHot(M[1:end-1, i])
            index = findfirst(isone, M[:, i])
            basis[index] = i
        end
    end
    @assert !any(t-> t == -1, basis) "problem not caconical"
    for i in 1:m
        j = basis[i]
        pivot!(M, i, j)
    end
    return basis
end
function simplexSolver(A::Matrix{T}, b::Vector, c::Vector; verbose::Bool = false) where T
    M = [A b; c' 0]
    basis = findInitialBasis!(M)
    k = 1
    nmax = 1000
    while !isoptimal(M) && k < nmax
        k+=1
        verbose && display(M)
        entering = enteringVar(M)
        entering == -1 && (println("------------"); return T[-1, -1])
        leaving = exitingVarIndex(M, entering)
        leaving == -1 && (println("------------"); return T[-1, -1])
        verbose && @show (entering, leaving)
        basis[leaving] = entering
        pivot!(M, leaving, entering)
    end
    verbose && display(M)
    m, n = size(M)
    xstar = zeros(T, n - 1)
    xstar[basis] = getxB(M)
    return xstar
end

simplexSolver (generic function with 1 method)

In [9]:
function  devoir3_4()
    
    A=[1//1 1 1 0 ; 
          -1 -1 0 1;
    ]
    
    b=[1, -2]
    
    c = [0, 0, 1, 1]
    simplexSolver(A, b, c, verbose=true)
end

devoir3_4()

3×5 Matrix{Rational{Int64}}:
  1//1   1//1  1//1  0//1   1//1
 -1//1  -1//1  0//1  1//1  -2//1
  0//1   0//1  0//1  0//1   1//1

4-element Vector{Rational{Int64}}:
  0//1
  0//1
  1//1
 -2//1